version: '3.1'

services:
  yap-bots:
    build: .
    restart: always
    ports:
      - 8005:80
    volumes:
      - .:/var/www/html/
      - ./logs/:/var/log/apache2
    environment:
      ENVIRONMENT: dev
  yap_bots_db:
    image: mariadb:10.11
    restart: always
    ports:
      - 3116:3306
    environment:
      MARIADB_ROOT_PASSWORD: yap_bots_root_password
      MARIADB_DATABASE: yap_bots
      MARIADB_USER: yap_bots_user
      MARIADB_PASSWORD: yap_bots_password
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/init.sql
