version: '3.1'

services:
  yap-bots:
    build: .
    restart: always
    ports:
      - 8005:80
    volumes:
      - .:/var/www/html/
    environment:
      ENVIRONMENT: dev
  yap_bots_db:
    image: mysql:5.5
    restart: always
    ports:
      - 3116:3306
    environment:
      MYSQL_ROOT_PASSWORD: yap_bots_root_password
      MYSQL_DATABASE: yap_bots
      MYSQL_USER: yap_bots_user
      MYSQL_PASSWORD: yap_bots_password
