version: '3.1'

services:
  yap-bots:
    build: .
    restart: always
    ports:
      - 8005:80
    volumes:
      - .:/var/www/html/
    environment:
      ENVIRONMENT: dev
    links:
      - redis
  redis:
    image: redis
    restart: always
#  yap_db:
#    image: mysql:5.5
#    restart: always
#    ports:
#      - 3106:3306
#    environment:
#      MYSQL_ROOT_PASSWORD: yap_root_password
#      MYSQL_DATABASE: yap
#      MYSQL_USER: yap_user
#      MYSQL_PASSWORD: yap_password